ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.ktproject.ApplicationKt.module ]
    }
}

jwt {
    secret = "your_jwt_secret"
    issuer = "ktor-autoservice"
    audience = "ktor-users"
    realm = "ktor"
}

# db {
#     driverClassName = "org.h2.Driver"
#     jdbcURL = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
#     maximumPoolSize = 3
#     autoCommit = false
#     username = "root"
#     password = ""
# }
